[tool.poetry]
name = "mwbot"
version = "0.1.0"
description = "为PRTS和ArcaeaCNWiki提供编辑功能的Mediawiki API库"
authors = ["咕咕mur <2221533105@qq.com>"]
license = "MIT"
repository = "https://github.com/GuGuMur/mwbot"

readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.23.3"
ujson = "^5.7.0"
loguru = "^0.6.0"
schedule = "^1.1.0"
aiohttp = "^3.8.3"
mwparserfromhell = "^0.6.4"
regex = "^2022.10.31"
pendulum = "^2.1.2"
mako = "^1.2.4"
asyncio = "^3.4.3"


[[tool.poetry.source]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = false
secondary = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[package.source]
type = "git"
url = "ssh://git@github.com/GuGuMur/mwbot.git"